spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easy_travel?serverTimezone=UTC
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
