spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/easy_travel_reservations?serverTimezone=UTC
    url: jdbc:mysql://mysql-reservated-travels:3305/easy_travel_reservations?serverTimezone=UTC
